import { fetchContent, fileExists, path, write } from "./fileManager.js";
import { init, overrideAutoCommand } from "./Vim.js";

export class Builder {
	// Config Manager
	
	fetchSavedConfig(
		config: string = "editingConfig"
	): Object {
		const name = !config.includes(".json") ? `${config}.json` : config;

		if (!fileExists(path(["configs", name]))) write("{ }", ["configs", name]);
		return JSON.parse(fetchContent(["configs", name]));
	}

	updateConfig(
		data: [string, any], // [Name, Data: <any>]
		config: string = "editingConfig"
	) {
		const name = !config.includes(".json") ? `${config}.json` : config;
		const cached = Object.assign(this.fetchSavedConfig(), {
			[data[0]]: data[1]
		});

		write(JSON.stringify(cached, null, 2), ["configs", name])
	}

	buildConfig(
		data: Object
	) {
		if (Object.keys(data).length === 0) {
			console.log("~ Your config cannot be empty ~");
			console.log("~ Add at least one thing before pushing changes.\n");
		} else {
			const supportedKeys = [
				"launchermessage"
			]

			for (const [key, value] of Object.entries(data)) {
				if (supportedKeys.includes(key.toLowerCase())) {
					switch (key.toLowerCase()) {
						case "launchermessage":
							this.updateNeovimOutput(overrideAutoCommand("\"VimEnter\"", `print(\"${value}\")`));
							break;
					}
				}
			}
		}
	}

	private updateNeovimOutput(
		content: string,
		overrideDuplicates: boolean = true
	) {
		let currentSource = `-- This Neovim configuration was auto-generated. --\n--[[\n\n	Generated by: https://github.com/transicle/Neovim-config-helper\n	Generated in: Lua\n\n]]--\n\n${fetchContent(init)}`;
		currentSource += content;
		
		write(currentSource, init, true);
	}

	// Constructor

	changeLauncherMessage(
		content: string
	) {
		this.updateConfig(["launcherMessage", content]);
	}
}
