export type AsciiArtFonts =
  | "Standard"
  | "Block"
  | "Banner"
  | "Big"
  | "Small"
  | "Slant"
  | "Lean"
  | "Shadow"
  | "Digital"
  | "Bubble"
  | "3D"
  | "3x5"
  | "Acrobatic"
  | "Alligator"
  | "Alligator2"
  | "Alpha"
  | "AMC 3 Line"
  | "AMC AAA01"
  | "AMC Neko"
  | "AMC Razor"
  | "AMC Slash"
  | "AMC Thin"
  | "Avatar"
  | "Banner3-D"
  | "Banner3"
  | "Banner4"
  | "Barbwire"
  | "Basic"
  | "Bell"
  | "Big Chief"
  | "Big Money-ne"
  | "Big Money-nw"
  | "Big Money-se"
  | "Big Money-sw"
  | "Blocky"
  | "Bolger"
  | "Braced"
  | "Bright"
  | "Broadway"
  | "Bulbhead"
  | "Caligraphy"
  | "Cards"
  | "Catwalk"
  | "Chiseled"
  | "Chunky"
  | "Mini"
  | "Short"
  | "Small Caps"
  | "Smkeyboard"
  | "Smscript"
  | "Smshadow"
  | "Smtengwar"
  | "Term"
  | "Thin"
  | "Cosmic"
  | "Crazy"
  | "Crick"
  | "Cricket"
  | "Cursive"
  | "Cyberlarge"
  | "Cybermedium"
  | "Cybersmall"
  | "Def Leppard"
  | "Diamond"
  | "Digs"
  | "Doh"
  | "DOS Rebel"
  | "Efti Chess"
  | "Efti Font"
  | "Efti Italic"
  | "Efti Piti"
  | "Efti Robot"
  | "Efti Wall"
  | "Efti Water"
  | "Epic"
  | "Fender"
  | "Gothic"
  | "Graceful"
  | "Graffiti"
  | "Hex"
  | "Hieroglyphs"
  | "Hollywood"
  | "Invita"
  | "Isometric1"
  | "Isometric2"
  | "Isometric3"
  | "Isometric4"
  | "Jacky"
  | "Jazmine"
  | "Kban"
  | "Keyboard"
  | "Knob"
  | "Kool"
  | "Larry 3D"
  | "Letters"
  | "Line Blocks"
  | "Linux"
  | "Lockergnome"
  | "Madrid"
  | "Marquee"
  | "Merlin1"
  | "Merlin2"
  | "Morse"
  | "Moscow"
  | "Nancyj"
  | "Nancyj-fancy"
  | "Nancyj-improved"
  | "Nancyj-underlined"
  | "Nipples"
  | "O8"
  | "Ogre"
  | "Old Banner"
  | "Pagga"
  | "Patorjk’s Cheese"
  | "Pawp"
  | "Peaks"
  | "Pebbles"
  | "Pepper"
  | "Poison"
  | "Puffy"
  | "Puzzle"
  | "Pyramid"
  | "Rammstein"
  | "Rectangles"
  | "Roman"
  | "Script"
  | "Serifcap"
  | "Shimrod"
  | "Smisome1"
  | "Speed"
  | "Spliff"
  | "S-relief"
  | "Star Wars"
  | "Stellar"
  | "Stop"
  | "Straight"
  | "Swamp Land";