/*

		  Neovize ~ A JavaScript Neovim configuration handler
	~ Support us on GitHub @ https://github.com/transicle/Neovize ~

*/

import { fetchContent, fileExists, path, write } from "../fileManager.js";
import type { Config } from "../types.js";
import { merge } from "../utility.js";
import { init, overrideAutoCommand, saveOldConfig } from "../Vim/Vim.js";
import { Dashboard } from "./Dashboard.js";

export function fetchSavedConfig(
	config: string = "editingConfig"
): Config {
	const name = !config.includes(".json") ? `${config}.json` : config;

	if (!fileExists(path(["configs", name])) || fetchContent(["configs", name]).trim() === "") write("{ }", ["configs", name]);
	return JSON.parse(fetchContent(["configs", name])) as Config;
}

export function updateConfig<K extends keyof Config>(
	data: [K, any],
	config: string = "editingConfig"
) {
	const name = !config.includes(".json") ? `${config}.json` : config;
	const cached: Config = fetchSavedConfig();

	merge(cached, { [data[0]]: data[1] });
	write(JSON.stringify(cached, null, 2), ["configs", name]);
}

export class Builder {
	buildConfig(
		data: Object
	) {
		if (Object.keys(data).length === 0) {
			console.log("[!] Your config cannot be empty. ~");
			console.log("[!] Add at least one thing before pushing changes.\n");
		} else {
			saveOldConfig();
			console.log("[/] Building new Neovize configuration ...");

			const supportedKeys = [
				"launchermessage", "dashboard", "packages"
			]

			for (const [key, value] of Object.entries(data)) {
				if (supportedKeys.includes(key.toLowerCase())) {
					console.log(`[/] Updating "${key}" ...`);
					switch (key.toLowerCase()) {
						case "launchermessage":
							this.updateNeovimOutput(overrideAutoCommand("\"VimEnter\"", `print(\"${value}\")`));
							console.log(`[!] Set "${key}" key to "${value}".`);
							break;
						case "dashboard":
							
							console.log(`[!] Applied all changes to the dashboard.`);
							break;
					}
				}
			}

			console.log("[~] Neovize configuration built. :)");
		}
	}

	private updateNeovimOutput(
		content: string
	) {
		let currentSource = `-- This Neovim configuration was auto-generated. --\n--[[\n\n	Generated by: https://github.com/transicle/Neovize\n	Generated in: Lua\n\n]]--\n\n`;
		const commentRegex = /^-- This Neovim configuration was auto-generated\. --\n--\[\[[\s\S]*?\]\]--\n*/m;
		const strippedContent = content.replace(commentRegex, "");

		currentSource = currentSource + strippedContent;

		write(currentSource, init, true);
	}

	// Bigger configurations

	DashboardController = Dashboard;

	// Small configurations, no extra classes needed.
	/**
	 * 
	 * Changes the message you see in the commandline when you first launch Neovim.
	 * 
	 * @warning This does **not** change the main default message! Use the **`DashboardController`** class for that.
	 */
	changeLauncherMessage(
		content: string
	) {
		updateConfig(["launcherMessage", content]);
	}
}
