/*

		  Neovize ~ A JavaScript Neovim configuration handler
	~ Support us on GitHub @ https://github.com/transicle/Neovize ~

*/

import { fetchContent, fileExists, newFolder, path, write } from "../fileManager.js";
import type { Config } from "../types.js";
import { merge } from "../utility.js";
import { importAlpha } from "../Vim/Alpha.nvim.js";
import { importPackage } from "../Vim/packageManager.js";
import { init, overrideAutoCommand, overridePackage, saveOldConfig } from "../Vim/Vim.js";
import { Dashboard } from "./Dashboard.js";

/**
 * 
 * Returns the configuration file that should be edited.
 * 
 * By default, this will return the standard "editingConfig.json" configuration file.
 * 
 * @note It's highly recommended you stick using this function. Some code in Neovize depends on the "editingConfig.json" file itself, especially when hardcoding values.
 */
export function fetchSavedConfig(
	config: string = "editingConfig"
): Config {
	if (!fileExists(path(["configs"]))) newFolder(["configs"]);
	const name = !config.includes(".json") ? `${config}.json` : config;

	if (!fileExists(path(["configs", name])) || fetchContent(["configs", name]).trim() === "") write("{ }", ["configs", name]);
	return JSON.parse(fetchContent(["configs", name])) as Config;
}

/**
 * 
 * Update the chosen configuration file with built in
 *  handling for nested objects and TypeScript type declarations.
 * 
 * @note Although deprecated, this function should be preferred in some use cases, such as when the desired object does not currently exist.
 * @deprecated Usage of this function is not recommended. Instead, try writing directly to the desired file.
 */
export function updateConfig<K extends keyof Config>(
	data: [K, any],
	config: string = "editingConfig"
) {
	const name = !config.includes(".json") ? `${config}.json` : config;
	const cached: Config = fetchSavedConfig();

	merge(cached, { [data[0]]: data[1] });
	write(JSON.stringify(cached, null, 2), ["configs", name]);
}

/**
 * 
 * Neovize's main construction class. Configure your entire Neovize configuration using this class.
 */
export class Builder {
	buildConfig() {
		const data = fetchSavedConfig();
		if (Object.keys(data).length === 0) {
			console.log("[!] Your config cannot be empty. ~");
			console.log("[!] Add at least one thing before pushing changes.\n");
		} else {
			saveOldConfig();
			console.log("[/] Building new Neovize configuration ...");

			const supportedKeys = [
				"launchermessage", "dashboard"
			]

			for (const [key, value] of Object.entries(data)) {
				if (supportedKeys.includes(key.toLowerCase())) {
					console.log(`[/] Updating "${key}" ...`);
					switch (key.toLowerCase()) {
						case "launchermessage":
							this.updateNeovimOutput(overrideAutoCommand("\"VimEnter\"", `print(\"${value}\")`));
							console.log(`[!] Set "${key}" key to "${value}".`);
							break;
						case "dashboard":
							this.updateNeovimOutput(overridePackage(importAlpha(), "goolord/alpha-nvim"));
							console.log(`[!] Applied all changes to the dashboard.`);
							break;
					}
				}
			}

			for (const plugin of this.packageData) {
				this.updateNeovimOutput(overridePackage(plugin[1]!, plugin[0]!));
			}

			console.log("[~] Neovize configuration built. :)");
		}
	}

	private updateNeovimOutput(
		content: string
	) {
		let currentSource = `\n\n-- This Neovim configuration was auto-generated. --\n--[[\n\n    Generated by: https://github.com/transicle/Neovize\n    Generated in: Lua\n\n]]--${this.packageData.length > 0 ? "\n\n" : ""}`;
		const commentRegex = /^-- This Neovim configuration was auto-generated\. --\n--\[\[[\s\S]*?\]\]--\n*/m;
		let strippedContent = content.replace(commentRegex, "");

		currentSource = currentSource + strippedContent;

		write(currentSource.trim(), init, true);
	}

	// Bigger configurations

	DashboardController = Dashboard;

	// Small configurations, no extra classes needed.
	/**
	 * 
	 * Changes the message you see in the commandline when you first launch Neovim.
	 * 
	 * @warning This does **not** change the main default message! Use the **`DashboardController`** class for that.
	 */
	changeLauncherMessage(
		content: string
	) {
		updateConfig(["launcherMessage", content]);
	}

	private packageData: string[][] = [];
	/**
	 * 
	 * Install a custom package not natively included in Neovize using the Neovize Plugin Manager (NPM).
	 * 
	 * @note As of **October 10th, 2025**: Only **GitHub** repositories are supported. 
	 */
	downloadPackage(
		repository: string,
		body: string = ""
	) {
		const details = importPackage(repository, body);

		this.packageData.push([repository, details]);
		console.log(`[!] Successfully downloaded package: "${repository}"`);
	}
}
